export const FontHelveticaNeue = {
  italic: "HelveticaNeue-Italic",
  ultraLight: "HelveticaNeue-UltraLight",
  ultraLightItalic: "HelveticaNeue-UltraLightItalic",
  light: "HelveticaNeue-Light",
  lightItalic: "HelveticaNeue-LightItalic",
  regular: "HelveticaNeue-Regular",
  medium: "HelveticaNeue-Medium",
  boldItalic: "HelveticaNeue-BoldItalic",
  bold: "HelveticaNeue-Bold",
  condensedBold: "HelveticaNeue-CondensedBold",
};

export const ICONS = {
  ic_multiplication: require("./icons/ic_multiplication.png"),
  ic_change_table: require("./icons/ic_change_table.png"),
  ic_cancel_order: require("./icons/ic_cancel_order.png"),
  ic_merge_order: require("./icons/ic_merge_order.png"),
  ic_split_order: require("./icons/ic_split_order.png"),
  ic_add_new_invoice: require("./icons/ic_add_new_invoice.png"),
  ic_request_payment: require("./icons/ic_request_payment.png"),
  ic_dollar: require("./icons/ic_dollar.png"),
  ic_wallet: require("./icons/ic_wallet.png"),
  ic_cash: require("./icons/ic_cash.png"),
  ic_visa: require("./icons/ic_visa.png"),
  ic_mastercard: require("./icons/ic_mastercard.png"),
  ic_atm_card: require("./icons/ic_atm_card.png"),
  ic_card: require("./icons/ic_card.png"),
  ic_list: require("./icons/ic_list.png"),
  ic_customer: require("./icons/ic_customer.png"),
  ic_save: require("./icons/ic_save.png"),
  ic_delivery_invoice: require("./icons/ic_delivery_invoice.png"),
  ic_take_awake_invoice: require("./icons/ic_take_awake_invoice.png"),
  ic_bag: require("./icons/ic_bag.png"),
  ic_money: require("./icons/ic_money.png"),
  ic_in_table_item: require("./icons/ic_in_table_item.png"),
  ic_take_awake_home: require("./icons/ic_take_awake_home.png"),
  ic_in_table_home: require("./icons/ic_in_table_home.png"),
  ic_delivery_home: require("./icons/ic_delivery_home.png"),
  ic_all_home: require("./icons/ic_all_home.png"),
  ic_delivery_home_focus: require("./icons/ic_delivery_home_focus.png"),
  ic_take_awake_home_focus: require("./icons/ic_take_awake_home_focus.png"),
  ic_in_table_home_focus: require("./icons/ic_in_table_home_focus.png"),
  ic_all_home_focus: require("./icons/ic_all_home_focus.png"),
  ic_ims: require("./icons/ic_ims.png"),
  ic_profile: require("./icons/ic_profile.png"),
  ic_payment: require("./icons/ic_payment.png"),
  ic_management_order: require("./icons/ic_management_order.png"),
  ic_table_room: require("./icons/ic_table_room.png"),
  ic_home: require("./icons/ic_home.png"),
  ic_logout: require("./icons/ic_logout.png"),
  ic_clause: require("./icons/ic_clause.png"),
  ic_sync: require("./icons/ic_sync.png"),
  ic_support: require("./icons/ic_support.png"),
  ic_settingProfile: require("./icons/ic_settingProfile.png"),
  ic_showTable: require("./icons/ic_showTable.png"),
  ic_settingBuy: require("./icons/ic_settingBuy.png"),
  ic_print: require("./icons/ic_print.png"),
  ic_notification: require("./icons/ic_notification.png"),
  ic_instruct: require("./icons/ic_instruct.png"),
  ic_changePass: require("./icons/ic_changePass.png"),
  ic_language: require("./icons/ic_language.png"),
  ic_settingNotification: require("./icons/ic_settingNotification.png"),
  ic_arrowRight: require("./icons/ic_arrowRight.png"),
  ic_chooseRound: require("./icons/ic_chooseRound.png"),
  ic_round: require("./icons/ic_round.png"),
  ic_vietNam: require("./icons/ic_vietNam.png"),
  ic_english: require("./icons/ic_english.png"),
  ic_cook: require("./icons/ic_cook.png"),
  ic_bill: require("./icons/ic_bill.png"),
  ic_bikeShip: require("./icons/ic_bikeShip.png"),
  ic_listTable: require("./icons/ic_listTable.png"),
  ic_teamPeople: require("./icons/ic_teamPeople.png"),
  ic_timeTable: require("./icons/ic_timeTable.png"),
  ic_temTable: require("./icons/ic_temTable.png"),
  ic_priceTable: require("./icons/ic_priceTable.png"),
  ic_filter: require("./icons/ic_filter.png"),
  ic_take: require("./icons/ic_take.png"),
};

export const enum SoundBundle {
  /** mp3 */
  DEFAULT = "default_sound",
  /** mp3 */
  NEW_BOOKING = "new_booking",
  /** mp3 */
  NEW_BOOKING_LOW = "new_booking_low",
  /** mp3 */
  OPEN_APP_NOW = "open_app_now",
}
